# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rescale_to_coverage <- function(cdf, coverage, Mid_Week) {
    .Call(`_mypackage_rescale_to_coverage`, cdf, coverage, Mid_Week)
}

incremental_cov_leakage <- function(x, y) {
    .Call(`_mypackage_incremental_cov_leakage`, x, y)
}

impact_time_week <- function(x, y, z, a, b, c) {
    .Call(`_mypackage_impact_time_week`, x, y, z, a, b, c)
}

cumulative_covC <- function(x) {
    .Call(`_mypackage_cumulative_covC`, x)
}

incremental_covC <- function(x) {
    .Call(`_mypackage_incremental_covC`, x)
}

